### ISSUE TITLE
module:enable doesn't work

### ISSUE THREAD

**Issue by ManoloPina** [caffeinated/modules#152]
My module is disable trying to use php artisan module:enable [slug-my-module] doesn't make any changes.

**Comment by kaidesu** [comment]
can you post your module manifest file here as well as the name of your modules directory?

---

e.g.
**Directory:**
`Themes/`

**Manifest:**
```json
{
    "name": "Themes",
    "slug": "themes",
    "version": "0.1-alpha",
    "description": "Easily change the look and feel of the website for both the frontend and backend.",
    "order": 5,
}
```

**Comment by siksniraps** [comment]
I think I have a similar problem. 
All modules except for one work fine, but one is stuck on Disabled.
When I run `php artisan module:enable` it says that _"Module is already enabled."_ and when I try to run `php artisan module:disable` it says _"Module is already disabled."_
php artisan module:list always shows the module as Disabled.
My module manifest:
```
{
	"name": "Messaging",
	"slug": "messaging",
	"version": "1.0",
	"description": "Direct messaging module",
	"enabled": true
}
```

**Comment by siksniraps** [comment]
Problem was resolved by creating a new module and copying all old files back. No idea what was wrong. All files in the new module are the same, slug and module name as well.
The module was originally created by a different developer though and I received with git.

**Comment by kaidesu** [comment]
@siksniraps what version of the package are you using? With 3.x I've implemented caching, so you no longer need to include the `enabled` key within your module's manifest file.

Running `php artisan module:optimize` will update the cache (which is located in your application storage directory with the name of `modules.json`). The package will manage the enabled/disabled state within the cached file - that way you don't need to commit `enabled` with your module to git.

**Comment by cyrilmarois** [comment]
@kaidesu running the command <code>php artisan module:optimize</code> does not exists and <code>php artisan optimize</code> does not solve the issue neither. I'm using the version v2.2.4 with laravel v5.2.29

**Comment by sl4wa** [comment]
I had the same issue today. Using version ~2.0. Running command `php artisan module:cache` helped

**Comment by acccims** [comment]
php artisan module:make is not recognised using version 3.0.6....how do i solve it?
